default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: vitaliikablukov

development:
  <<: *default
  database: rubyshop_dev

test:
  <<: *default
  database: rubyshop_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
